*** Variables ***
${USERNAME}         xpath=//*[@class='android.widget.EditText']
${BUTOON_LOGIN}     xpath=//android.widget.ImageButton[@content-desc="Next"]
${WELCOME_TEXT}     xpath=//*[@resource-id='com.obs.android.olm.localmachine.dev:id/nav_welcome_text']
${MORE_OPTION}      xpath=//android.widget.ImageView[@content-desc="More options"]
${LOGOUT_BUTTON}    xpath=//android.widget.TextView[@text='Log Out' and @resource-id='com.obs.android.olm.localmachine.dev:id/title']
